# Generated by Django 4.1.4 on 2022-12-14 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0003_alter_group_members"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Chatroom",
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="topic",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="group",
            new_name="chatroom",
        ),
    ]
